query GetPrivateQuery($id: UUID!) {
  organization {
    getPrivate(id: $id) {
      name
      acl {
        permissions {
          __typename
          id
          withPermissions {
            __typename
            ... on Inherit {
              from
            }
            ... on Permissions {
              read
              write
            }
          }
        }
        default {
          __typename
          ... on Inherit {
            from
          }
          ... on Permissions {
            read
            write
          }
        }
      }
    }
  }
}