query GetVersionPrivateQuery($id: Uuid!, $version: Int!) {
  organization {
    getVersionPrivate(id: $id, version: $version) {
      name
      acl {
        permissions {
          __typename
          id
          withPermissions {
            __typename
            ... on Inherit {
              from
            }
            ... on Permissions {
              read
              write
            }
          }
        }
        default {
          __typename
          ... on Inherit {
            from
          }
          ... on Permissions {
            read
            write
          }
        }
      }
    }
  }
}