[package]
name = "semio-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
semio-record = { git = "https://github.com/semio-ai/semio-record.git", branch = "main" }
semio-store-rpc = { git = "https://github.com/semio-ai/semio-store-rpc.git", branch = "main" }
anyhow = "1"
indexmap = { version = "2", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "3", features = ["derive"] }
futures = "0.3"
graphql_client = "0.10"
lazy_static = "1"
reqwest = { version = "0.13", features = ["json"] }
semver = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
termios = "0.3"
tokio = { version = "1", features = ["full"] }
uuid = "1"
