query GetVersionPublicQuery($id: UUID!, $version: Int!) {
  enumeration {
    getVersionPublic(id: $id, version: $version) {
      __typename
      parent
      name
      variants {
        id
        variant {
          __typename
          name
          type {
            ...UnfrozenTyFields
          }
        }
      }
    }
  }
}

fragment UnfrozenTyFields on UnfrozenTy {
  __typename
  ... on Primitive {
    kind
  }
  ... on UnfrozenScalar {
    reference {
      __typename
      id
      versionReq
    }
  }
  ... on UnfrozenArray {
    reference {
      __typename
      id
      versionReq
    }
  }
  ... on UnfrozenOption {
    element {
      ...UnfrozenTyElementFields
    }
  }
}

fragment UnfrozenTyElementFields on UnfrozenTy {
  __typename
  ... on Primitive {
    kind
  }
  ... on UnfrozenScalar {
    reference {
      __typename
      id
      versionReq
    }
  }
  ... on UnfrozenArray {
    reference {
      __typename
      id
      versionReq
    }
  }
}
