query GetVersionFrozenQuery($id: UUID!, $version: Int!) {
  enumeration {
    getVersionFrozen(id: $id, version: $version) {
      __typename
      parent
      name
      variants {
        __typename
        id
        variant {
          __typename
          name
          type {
            __typename
            ... on Primitive {
              kind
            }
            ... on FrozenScalar {
              reference {
                __typename
                id
                version
              }
            }
            ... on FrozenArray {
              reference {
                __typename
                id
                version
              }
            }
          }
        }
      }
    }
  }
}