query GetPrivateQuery($id: UUID!) {
  enumeration {
    getPrivate(id: $id) {
      __typename
      acl {
        permissions {
          __typename
          id
          withPermissions {
            __typename
            ... on Inherit {
              from
            }
            ... on Permissions {
              read
              write
            }
          }
        }
        default {
          __typename
          ... on Inherit {
            from
          }
          ... on Permissions {
            read
            write
          }
        }
      }
      parent
      name
      variants {
        id
        variant {
          __typename
          name
          type {
            ...UnfrozenTyFields
          }
        }
      }
    }
  }
}

fragment UnfrozenTyFields on UnfrozenTy {
  __typename
  ... on Primitive {
    kind
  }
  ... on UnfrozenScalar {
    reference {
      __typename
      id
      versionReq
    }
  }
  ... on UnfrozenArray {
    reference {
      __typename
      id
      versionReq
    }
  }
  ... on UnfrozenOption {
    element {
      ...UnfrozenTyElementFields
    }
  }
}

fragment UnfrozenTyElementFields on UnfrozenTy {
  __typename
  ... on Primitive {
    kind
  }
  ... on UnfrozenScalar {
    reference {
      __typename
      id
      versionReq
    }
  }
  ... on UnfrozenArray {
    reference {
      __typename
      id
      versionReq
    }
  }
}
