query GetFrozenQuery($id: UUID!) {
  enumeration {
    getFrozen(id: $id) {
      __typename
      parent
      name
      variants {
        __typename
        id
        variant {
          __typename
          name
          type {
            ...FrozenTyFields
          }
        }
      }
    }
  }
}

fragment FrozenTyFields on FrozenTy {
  __typename
  ... on Primitive {
    kind
  }
  ... on FrozenScalar {
    reference {
      __typename
      id
      version
    }
  }
  ... on FrozenArray {
    reference {
      __typename
      id
      version
    }
  }
  ... on FrozenOption {
    element {
      ...FrozenTyElementFields
    }
  }
}

fragment FrozenTyElementFields on FrozenTy {
  __typename
  ... on Primitive {
    kind
  }
  ... on FrozenScalar {
    reference {
      __typename
      id
      version
    }
  }
  ... on FrozenArray {
    reference {
      __typename
      id
      version
    }
  }
}
