query GetPublicQuery($id: UUID!) {
  structure {
    getPublic(id: $id) {
      __typename
      name
      parent
      fields {
        __typename
        id
        field {
          __typename
          name
          type {
            __typename
            ... on Primitive {
              kind
            }
            ... on UnfrozenScalar {
              reference {
                __typename
                id
                versionReq
              }
            }
            ... on UnfrozenArray {
              reference {
                __typename
                id
                versionReq
              }
            }
          }
        }
      }
    }
  }
}