query TaggedQuery($id: Uuid!, $version: String!) {
  structure {
    tagged(id: $id, version: $version) {
      __typename
      parent
      name
      fields {
        __typename
        id
        field {
          __typename
          name
          type {
            __typename
            ... on Primitive {
              kind
            }
            ... on FrozenScalar {
              reference {
                __typename
                id
                version
              }
            }
            ... on FrozenArray {
              reference {
                __typename
                id
                version
              }
            }
          }
        }
      }
    }
  }
}