query GetPublicQuery($id: Uuid!) {
  module {
    getPublic(id: $id) {
      __typename
      parent
      name
      executable
      dependencies {
        id
        versionReq
      }
      exports {
        __typename
        id
        export {
          __typename
          name
          kind {
            __typename
            ... on Function {
              parameters {
                __typename
                id
                parameter {
                  __typename
                  name
                  type {
                    __typename
                    ... on Primitive {
                      kind
                    }
                    ... on UnfrozenScalar {
                      reference {
                        __typename
                        id
                        versionReq
                      }
                    }
                    ... on UnfrozenArray {
                      reference {
                        __typename
                        id
                        versionReq
                      }
                    }
                  }
                  mutable
                }
              }
              returnType {
                __typename
                ... on Primitive {
                  kind
                }
                ... on UnfrozenScalar {
                  reference {
                    __typename
                    id
                    versionReq
                  }
                }
                ... on UnfrozenArray {
                  reference {
                    __typename
                    id
                    versionReq
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}