query GetPrivateQuery($id: UUID!) {
  module {
    getPrivate(id: $id) {
      __typename
      acl {
        permissions {
          __typename
          id
          withPermissions {
            __typename
            ... on Inherit {
              from
            }
            ... on Permissions {
              read
              write
            }
          }
        }
        default {
          __typename
          ... on Inherit {
            from
          }
          ... on Permissions {
            read
            write
          }
        }
      }
      parent
      name
      executable
      dependencies {
        id
        versionReq
      }
      exports {
        __typename
        id
        export {
          __typename
          name
          kind {
            __typename
            ... on Function {
              parameters {
                __typename
                id
                parameter {
                  __typename
                  name
                  type {
                    ...UnfrozenTyFields
                  }
                  mutable
                }
              }
              returnType {
                ...UnfrozenTyFields
              }
            }
          }
        }
      }
    }
  }
}

fragment UnfrozenTyFields on UnfrozenTy {
  __typename
  ... on Primitive {
    kind
  }
  ... on UnfrozenScalar {
    reference {
      __typename
      id
      versionReq
    }
  }
  ... on UnfrozenArray {
    reference {
      __typename
      id
      versionReq
    }
  }
  ... on UnfrozenOption {
    element {
      ...UnfrozenTyElementFields
    }
  }
}

fragment UnfrozenTyElementFields on UnfrozenTy {
  __typename
  ... on Primitive {
    kind
  }
  ... on UnfrozenScalar {
    reference {
      __typename
      id
      versionReq
    }
  }
  ... on UnfrozenArray {
    reference {
      __typename
      id
      versionReq
    }
  }
}
