query GetVersionFrozenQuery($id: UUID!, $version: Int!) {
  module {
    getVersionFrozen(id: $id, version: $version) {
      __typename
      parent
      name
      executable
      dependencies {
        id
        version
      }
      exports {
        __typename
        id
        export {
          __typename
          name
          kind {
            __typename
            ... on FrozenFunction {
              parameters {
                __typename
                id
                parameter {
                  __typename
                  name
                  type {
                    ...FrozenTyFields
                  }
                  mutable
                }
              }
              returnType {
                ...FrozenTyFields
              }
            }
          }
        }
      }
    }
  }
}

fragment FrozenTyFields on FrozenTy {
  __typename
  ... on Primitive {
    kind
  }
  ... on FrozenScalar {
    reference {
      __typename
      id
      version
    }
  }
  ... on FrozenArray {
    reference {
      __typename
      id
      version
    }
  }
  ... on FrozenOption {
    element {
      ...FrozenTyElementFields
    }
  }
}

fragment FrozenTyElementFields on FrozenTy {
  __typename
  ... on Primitive {
    kind
  }
  ... on FrozenScalar {
    reference {
      __typename
      id
      version
    }
  }
  ... on FrozenArray {
    reference {
      __typename
      id
      version
    }
  }
}
