query TaggedQuery($id: Uuid!, $version: String!) {
  module {
    tagged(id: $id, version: $version) {
      __typename
      parent
      name
      executable
      dependencies {
        id
        version
      }
      exports {
        __typename
        id
        export {
          __typename
          name
          kind {
            __typename
            ... on FrozenFunction {
              parameters {
                __typename
                id
                parameter {
                  __typename
                  name
                  type {
                    __typename
                    ... on Primitive {
                      kind
                    }
                    ... on FrozenScalar {
                      reference {
                        __typename
                        id
                        version
                      }
                    }
                    ... on FrozenArray {
                      reference {
                        __typename
                        id
                        version
                      }
                    }
                  }
                  mutable
                }
              }
              returnType {
                __typename
                ... on Primitive {
                  kind
                }
                ... on FrozenScalar {
                  reference {
                    __typename
                    id
                    version
                  }
                }
                ... on FrozenArray {
                  reference {
                    __typename
                    id
                    version
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}